## Mathematics Attitudes and Perceptions Survey
## Maciejewski and Thomas 2016 
## DOI: 10.1080/0020739X.2015.1133854

## we drop 12, 25, 26, 27, 32 - the "interest" subscale.

library(tidyverse)
library(readxl)
library(gghighlight)
library(ggtext)

MDXcolours <- c("#e30613","#2f2552","#ff4f00","#f47d07","#e50059","#6f6f6f","#000000")
MDXcolours2 <- c("#e30613","#2f2552", "#f5a623", "#6ba539","#00a3e0", "#f45d50", "#8e44ad" ) ## Generated by ChatGPT
carto <- c("#88CCEE","#CC6677","#DDCC77","#117733","#332288","#AA4499","#44AA99","#999933","#882255","#661100","#6699CC","#888888") ## https://carto.com/carto-colors/

data <- read_excel("Questionnaire data.xlsx")


MAPS_long <- c("After I study a topic in maths and feel that I understand it, I have difficulty solving problems on the same topic.",
"There is usually only one correct approach to solving a maths problem.",
"I'm satisfied if I can do the exercises for a maths topic, even if I don't understand how everything works.",
"I do not expect formulas to help my understanding of mathematical ideas, they are just for doing calculations.",
"Maths ability is something about a person that cannot be changed very much.",
"Nearly everyone is capable of understanding maths if they work at it.",
"Understanding maths means being able to recall something you've read or been shown.",
"If I am stuck on a maths problem for more than ten minutes, I give up or get help from someone else.",
"I expect the answers to maths problems to be numbers.",
"If I don't remember a particular formula needed to solve a problem on a maths exam there's nothing much I can do to come up with it.",
"In maths, it is important for me to make sense out of formulas and procedures before I use them.",
"Learning maths changes my ideas about how the world works.",
"I often have difficulty organizing my thoughts during a maths test.",
"Reasoning skills used to understand maths can be helpful to me in everyday life.",
"To learn maths, the best approach for me is to memorize solutions to sample problems.",
"No matter how much I prepare, I am still not confident when taking math tests.",
"It is a waste of time to understand where maths formulas come from.",
"We use this question to discard the survey results of people who are not reading the questions. Please select Agree (not Strongly Agree) for this question.",
"I can usually figure out a way to solve maths problems.",
"School mathematics has little to do with what I experience in the real world.",
"Being good at mathematics requires natural (i.e. innate, inborn) intelligence in maths.",
"When I am solving a maths problem, if I can see a formula that applies then I don't worry about the underlying concepts.",
"If I get stuck on a maths problem, there is no chance that I will figure it out on my own.",
"All I need to solve a maths problem is to have the necessary formulas.",
"I get upset easily when I am stuck on a maths problem.",
"Showing intermediate steps for a maths problem is not important as long as I can find the correct answer.",
"For each person, there are maths concepts that they would never be able to understand, even if they tried.",
"I am a mathematician."
)

likert = data.frame(value = c("Strongly Disagree", "Disagree", "Neither Agree nor Disagree", "Agree", "Strongly Agree"),
                    positivity = -2:2)

questions <- data.frame(question = 1:33,
                        consensus = 1,
                        category = NA,
                        text = NA)

questions$consensus[1:5] <- -1
questions$consensus[7:10] <- -1
questions$consensus[14] <- -1
questions$consensus[16:18] <- -1
questions$consensus[21:24] <- -1
questions$consensus[26:32] <- -1

## No expert consensus on these questions
questions$consensus[c(19,22,31)] <- 0

## Categories
questions$category[c(5,6,22,31)] <- "Growth mindset"
questions$category[c(13,15,21)] <- "Real world"
questions$category[c(1,14,17,20)] <- "Confidence"
questions$category[c(12,26,32)] <- "Interest"
questions$category[c(8,10,24,29)] <- "Persistence"
questions$category[c(3,4,11,18,23)] <- "Sense making"
questions$category[c(2,7,9,16,28,30)] <- "Answers"
questions$category[c(25,27)] <- "No category"
questions$category[19] <- "Filter"
questions$category[33] <- "Identity"

questions$text[-c(12, 25, 26, 27, 32)] <- MAPS_long

data <- data |> rename(
  id = 1,
  start_time = 2,
  end_time = 3,
  email = 4,
  name =  5,
  consent = 6,
  join_year = 7,
  a_level_statement = 8,
  pre_maps = 9:36,
  choice = 37:42,
  problem = 43:48,
  ai = 49:54,
  reflection = 55:60,
  outreach = 61:66,
  communication = 67:72,
  university_statement = 73,
  post_maps = 74:101
)


data <- data |> select(-(2:6)) |> mutate(id = 1:n())

## Maps results
maps_results <- data |>
  select(id, matches("^pre|^post")) |>
  pivot_longer(cols = -1, names_sep = "maps", names_to = c("time","question")) |>
  mutate(time = str_remove(time, "_")) |>
  mutate(question = as.numeric(question)) |>
  mutate(question = case_when(
    question < 12 ~ question,
    question < 24 ~ question + 1,
    question < 28 ~ question + 4,
    question == 28 ~ question + 5
  )) |>
  left_join(questions) |>
  left_join(likert) |>
  mutate(maths_metric = consensus*positivity) |>
  #mutate(maths_metric = case_when(
  #  consensus*positivity>0 ~ 1,
  #  is.na(positivity) ~ NA,
  #  T ~ 0)) |> ## NSS style positivity measure
  filter(category != "Filter")

## Embolden overall.
overall <- maps_results |> filter(category != "Identity") |>
  group_by(time) |> summarise(score = mean(maths_metric, na.rm = TRUE)) |>
  mutate(category = "<b>Overall</b>") |> ungroup()

maps_results |>
  group_by(category, time) |>
  summarise(score = mean(maths_metric, na.rm = TRUE)) |> ungroup() |> add_row(overall) |>
  mutate(survey = case_when(
    category == "Identity" ~ "other",
    T ~ "MAPS"
  )) |>
  mutate(category = fct_rev(fct_relevel(category, c("<b>Overall</b>",
                                            "Sense making",
                                            "Real world",
                                            "Persistence",
                                            "Growth mindset",
                                            "Confidence",
                                            "Answers",
                                            "Identity")))) |>
  ggplot(aes(x = category, y = score)) +
  geom_segment(data = . %>% pivot_wider(names_from = time, values_from = score),
               aes(x = category, y = pre, yend = post),
               linewidth = 1
               ) +
  geom_point(aes(colour = time), size = 8) +
  coord_flip() +
  facet_grid(rows = vars(survey), scales = "free", space = "free") +
  labs(title = "MAPS and Identity",
       subtitle = "Comparing recollection of pre-university attitudes to current attitudes",
       y = "Mean Likert score",
       x = "") +
  theme_grey(base_size = 16) +
  scale_colour_manual(breaks = c("pre", "post"), labels = c("before university", "at time of survey"), values = MDXcolours) +
  scale_y_continuous(limits = c(0,2)) +
  theme(axis.text.y= element_markdown()) +
  theme(legend.position = "bottom") +
  geom_text(data = . %>% filter(time == "pre"),
            aes(label = scales::number(score, accuracy = 0.01)), nudge_y = -0.1) +
  geom_text(data = . %>% filter(time == "post"),
            aes(label = scales::number(score, accuracy = 0.01)), nudge_y= 0.1)

ggsave("overall.png", width = 1280, height = 720, units = "px", dpi = 96) # For slides
ggsave("overall.png", width = 17, height = 9.5, units = "cm", dpi = 330) # For A4

maps_results |> group_by(id, category, time) |> select(-value,-positivity) |>
  summarise(score = mean(maths_metric, na.rm = TRUE)) |>
  pivot_wider(names_from = time, values_from = score) |> 
  mutate(delta = post - pre) |> drop_na(delta) |>
  group_by(category) |>
  summarise(mean_delta = mean(delta, na.rm = TRUE), sd = sd(delta, na.rm = TRUE), n= n()) |>
  write_csv("by category.csv")
  

maps_results |> group_by(id, time) |> select(-value,-positivity) |>
  summarise(score = mean(maths_metric, na.rm = TRUE)) |>
  pivot_wider(names_from = time, values_from = score) |> 
  mutate(delta = post - pre) |> drop_na(delta) |>
  group_by(id) |>
  summarise(mean_delta = mean(delta, na.rm = TRUE)) |>
  ungroup() |>
  summarise(grand_mean_delta = mean(mean_delta, na.rm = TRUE),
            sd = sd(mean_delta, na.rm = TRUE),
            min = min(mean_delta, na.rm = TRUE),
            max = max(mean_delta, na.rm = TRUE),
            n= n()) |>
  write_csv("overall.csv")

## Overall MAPS-only results.

maps_results |> group_by(id, time) |> select(-value,-positivity) |>
  filter(category != "Identity") |>
  summarise(score = mean(maths_metric, na.rm = TRUE)) |>
  pivot_wider(names_from = time, values_from = score) |> view()
  mutate(delta = post - pre) |> drop_na(delta) |>
  group_by(id) |>
  summarise(mean_delta = mean(delta, na.rm = TRUE)) |>
  ungroup() |>
  summarise(grand_mean_delta = mean(mean_delta, na.rm = TRUE),
            sd = sd(mean_delta, na.rm = TRUE),
            min = min(mean_delta, na.rm = TRUE),
            max = max(mean_delta, na.rm = TRUE),
            n= n())

## Pre-posts descriptives: MAPS
maps_results |> group_by(id, time) |> select(-value,-positivity) |>
  filter(category != "Identity") |> 
  summarise(score = mean(maths_metric, na.rm = TRUE)) |>
  group_by(time) |>
  drop_na(score) |>
  summarise(mean_score = mean(score),
            sd = sd(score),
            min = min(score),
            max = max(score),
            n=n())

## Pre-posts descriptives: identity
maps_results |> group_by(id, time) |> select(-value,-positivity) |>
  filter(category == "Identity") |> 
  summarise(score = mean(maths_metric, na.rm = TRUE)) |>
  group_by(time) |>
  drop_na(score) |>
  summarise(mean_score = mean(score),
            sd = sd(score),
            min = min(score),
            max = max(score),
            n=n())

categories <- c("Confidence", "Answers", "Sense making", "Growth mindset", "Persistence", "Real world", "Identity")



## Statements
data |> select(id, contains("statement")) |> write_csv("statements.csv")

## Interventions

intervention_questions <- data.frame(question = 1:6,
                        consensus = 1,
                        text = NA)


intervention_questions$text <- c(
  "encountered",
  "made me more confident in mathematics",
  "(didn't) increase my anxiety",
  "helped me prepare for my career",
  "is an important part of mathematics",
  "free text"
)


intervention_questions$consensus[c(1,6)] <- 0
intervention_questions$consensus[3] <- -1


interventions_data <- data |>
  select(!matches("^pre")) |>
  select(!matches("^post")) |>
  select(!contains("statement")) |>
  select(!join_year) |> 
  pivot_longer(cols = -1, names_to = c("intervention","question"), names_pattern = "([a-z]+)([0-9]+)") |>
  mutate(question = as.numeric(question)) |>
  left_join(intervention_questions) |> 
  mutate(value = case_when(
    question == 1 & str_starts(value, "Yes") ~ "True",
    question == 1 & str_starts(value, "No") ~ "False",
    T ~ value
  )) |>
  left_join(likert) |>
  mutate(maths_metric = consensus*positivity) |>
  #mutate(maths_metric = case_when(
   # consensus*positivity>0 ~ 1,
  #  is.na(positivity) ~ NA,
  #  T ~ 0)) |> ## NSS style positivity measure
  mutate(intervention = case_when(
    intervention == "problem" ~ "problem solving",
    T ~ intervention
  ))

## Interventions (by teaching element)

interventions_data |> drop_na(value) |> filter(question %in% 2:5) |>
  filter(intervention %in% c("communication","outreach")) |>
  group_by(intervention,question) |>
  summarise(score = mean(maths_metric)) |>
  left_join(intervention_questions) |>
  ggplot() +
  geom_col(aes(x=text,y=score,fill = intervention), position = position_dodge()) +
  coord_flip() +
  labs(title = "Attitudes towards teaching methods",
       subtitle = "",
       y = "Likert score",
       x = "") +
  scale_fill_discrete(name = "Teaching method", type = carto) +
  geom_hline(yintercept=0) +
  theme_grey(base_size = 16)

ggsave("teaching methods comm and outreach.png", width = 1280, height = 720, units = "px", dpi = 96)

interventions_data |> drop_na(value) |> filter(question %in% 2:5) |>
  filter(intervention %in% c("communication","outreach")) |>
  group_by(intervention,question) |>
  summarise(score = mean(maths_metric), sd = sd(maths_metric), n= n()) |>
  left_join(intervention_questions, by = c("question" = "question")) |>
  write_csv("intervention comm and outreach.csv")


interventions_data |> drop_na(value) |> filter(question %in% 2:5) |>
  filter(!intervention %in% c("communication","outreach")) |>
  group_by(intervention,question) |>
  summarise(score = mean(maths_metric)) |>
  left_join(intervention_questions) |>
  ggplot() +
  geom_col(aes(x=text,y=score,fill = intervention), position = position_dodge()) +
  coord_flip() +
  labs(title = "Attitudes towards teaching methods",
       subtitle = "",
       y = "Likert score",
       x = "") +
  scale_fill_discrete(name = "Teaching method", type = carto) +
  geom_hline(yintercept=0) +
  theme_grey(base_size = 16)

ggsave("teaching methods other.png", width = 1280, height = 720, units = "px", dpi = 96)

interventions_data |> drop_na(value) |> filter(question %in% 2:5) |>
  filter(!intervention %in% c("communication","outreach")) |>
  group_by(intervention,question) |>
  summarise(score = mean(maths_metric), sd = sd(maths_metric), n= n()) |>
  left_join(intervention_questions, by = c("question" = "question")) |> view()
  write_csv("intervention other.csv")

## Interventions (individual students) - jittered

interventions_data |> drop_na(value) |> filter(question %in% 2:5) |>
  filter(intervention %in% c("communication","outreach")) |>
  left_join(intervention_questions) |>
  group_by(text,maths_metric,intervention) |>
  ggplot(aes(x=text,y=maths_metric, colour = intervention)) +
  geom_jitter(width = 0.2, height = 0.2, cex = 3) +
  coord_flip() +
  labs(title = "Attitudes towards teaching methods",
       subtitle = "",
       y = "Likert score",
       x = "") +
  facet_grid(rows = vars(intervention)) +
  scale_colour_discrete(name = "Teaching method", type = carto) +
  scale_size(range = c(5,10), breaks = c(2,4,6)) +
  geom_hline(yintercept=0) +
  theme_grey(base_size = 16) +
  theme(legend.position = "bottom")


ggsave("teaching methods individual comm and outreach jittered.png", width = 1280, height = 720, units = "px", dpi = 96)



interventions_data |> drop_na(value) |> filter(question %in% 2:5) |>
  filter(!intervention %in% c("communication","outreach")) |>
  left_join(intervention_questions) |>
  group_by(text,maths_metric,intervention) |>
  ggplot(aes(x=text,y=maths_metric, colour = intervention)) +
  geom_jitter(width = 0.2, height = 0.2, cex = 3) +
  coord_flip() +
  labs(title = "Attitudes towards teaching methods",
       subtitle = "",
       y = "Likert score",
       x = "") +
  facet_grid(rows = vars(intervention)) +
  scale_colour_discrete(name = "Teaching method", type = carto) +
  scale_size(range = c(5,10), breaks = c(2,5,8,11)) +
  geom_hline(yintercept=0) +
  theme_grey(base_size = 16) +
  theme(legend.position = "bottom")

ggsave("teaching methods individual other jitter.png", width = 1280, height = 720, units = "px", dpi = 96)


## Interventions comments
interventions_data |> filter(text == "free text", !is.na(value)) |> view()


